-- MVP reference schema.
-- UUID values are generated by the Node.js application with crypto.randomUUID().
-- Migrations must run as a one-off admin command, not automatically inside web startup.

CREATE TABLE groups (
    id uuid PRIMARY KEY,
    name varchar(120) NOT NULL,
    invite_code varchar(64) NOT NULL UNIQUE,
    timezone varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT groups_name_not_blank CHECK (char_length(btrim(name)) BETWEEN 1 AND 120)
);

CREATE TABLE participants (
    id uuid PRIMARY KEY,
    group_id uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    display_name varchar(80) NOT NULL,
    display_name_normalized varchar(80) NOT NULL,
    edit_token_hash char(64) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT participants_name_not_blank CHECK (char_length(btrim(display_name)) BETWEEN 1 AND 80),
    CONSTRAINT participants_group_name_unique UNIQUE (group_id, display_name_normalized)
);

CREATE TABLE polls (
    id uuid PRIMARY KEY,
    group_id uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    sequence_no integer NOT NULL,
    title varchar(160),
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    day_start time NOT NULL,
    day_end time NOT NULL,
    slot_minutes smallint NOT NULL,
    meeting_duration_minutes smallint NOT NULL DEFAULT 60,
    status varchar(16) NOT NULL,
    based_on_poll_id uuid REFERENCES polls(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    CONSTRAINT polls_sequence_positive CHECK (sequence_no > 0),
    CONSTRAINT polls_dates_valid CHECK (
        starts_on <= ends_on
        AND (ends_on - starts_on) BETWEEN 0 AND 6
    ),
    CONSTRAINT polls_day_window_valid CHECK (day_start < day_end),
    CONSTRAINT polls_slot_minutes_valid CHECK (slot_minutes IN (30, 60)),
    CONSTRAINT polls_meeting_duration_valid CHECK (
        meeting_duration_minutes BETWEEN 30 AND 240
        AND meeting_duration_minutes % slot_minutes = 0
    ),
    CONSTRAINT polls_status_valid CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT polls_closed_at_consistent CHECK (
        (status = 'OPEN' AND closed_at IS NULL)
        OR
        (status = 'CLOSED' AND closed_at IS NOT NULL)
    ),
    CONSTRAINT polls_group_sequence_unique UNIQUE (group_id, sequence_no)
);

CREATE UNIQUE INDEX polls_one_open_per_group_idx
    ON polls(group_id)
    WHERE status = 'OPEN';

CREATE TABLE poll_responses (
    id uuid PRIMARY KEY,
    poll_id uuid NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
    participant_id uuid NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    state varchar(16) NOT NULL DEFAULT 'DRAFT',
    confirmed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT poll_responses_state_valid CHECK (state IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT poll_responses_confirmation_consistent CHECK (
        (state = 'DRAFT' AND confirmed_at IS NULL)
        OR
        (state = 'CONFIRMED' AND confirmed_at IS NOT NULL)
    ),
    CONSTRAINT poll_responses_poll_participant_unique UNIQUE (poll_id, participant_id)
);

CREATE TABLE availability_intervals (
    id uuid PRIMARY KEY,
    response_id uuid NOT NULL REFERENCES poll_responses(id) ON DELETE CASCADE,
    local_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    kind varchar(20) NOT NULL,
    preference_direction varchar(16),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT availability_interval_time_valid CHECK (start_time < end_time),
    CONSTRAINT availability_interval_kind_valid CHECK (
        kind IN ('UNAVAILABLE', 'IF_NEEDED', 'PREFERRED')
    ),
    CONSTRAINT availability_interval_direction_valid CHECK (
        (
            kind = 'PREFERRED'
            AND preference_direction IN ('EARLIER', 'FLAT', 'LATER')
        )
        OR
        (
            kind <> 'PREFERRED'
            AND preference_direction IS NULL
        )
    )
);

CREATE INDEX polls_group_created_idx
    ON polls(group_id, created_at DESC);

CREATE INDEX poll_responses_poll_state_idx
    ON poll_responses(poll_id, state);

CREATE INDEX availability_intervals_response_date_time_idx
    ON availability_intervals(response_id, local_date, start_time);
